version: '3.1'

services:
  minha_cidade:
    ports:
      - '3233:3233'
    restart: always
    image: 'minha_cidade:latest'
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - ROOT=${ROOT}
    volumes:
      - ${ROOT}:/config/minha_cidade

  db:
    image: postgres:14
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${ROOT}/db:/var/lib/postgresql/data
      - ${HOME}:/_home
