version: '3.1'

services:
  minha_cidade:
    ports:
      - '3233:3233'
    restart: always
    image: 'minha_cidade:latest'
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
      - FOTO_SOLICITACAO_FOLDER=/fotos
      - CITIES_JSON_PATH=/cities.json
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_POST=${PG_PORT}
      - POSTGRES_USERNAME=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DATABASE=${DB_NAME}
    volumes:
      - ${CITIES_JSON_PATH}:/cities.json
      - ${FOTO_SOLICITACAO_FOLDER}:/fotos

  db:
    image: postgres:14
    restart: always
    ports:
      - ${PG_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${DB_DATA_ROOT}:/var/lib/postgresql/data
      - ${HOME}:/_home
