version: '3.1'

services:
  minha_cidade:
    ports:
      - '3233:3233'
    restart: always
    image: 'minha_cidade:latest'
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${PG_PORT}
      - POSTGRES_USERNAME=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DATABASE=${DB_NAME}
      - ROOT=${ROOT}
    volumes:
      - ${ROOT}:/config/minha_cidade

  db:
    image: postgres:14
    restart: always
    ports:
      - ${PG_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${ROOT}/db:/var/lib/postgresql/data
      - ${HOME}:/_home
